# Generated by Django 2.2 on 2019-12-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentsData",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=130)),
                ("roll", models.CharField(max_length=50)),
                ("section", models.CharField(max_length=30)),
                ("classno", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_no", models.CharField(max_length=14)),
                ("password_hash", models.CharField(max_length=130)),
            ],
            options={"db_table": "attendance_studentsdata",},
        ),
    ]
