# Generated by Django 3.0 on 2019-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid", models.IntegerField()),
                ("cid", models.IntegerField(db_index=True)),
                ("date", models.DateField(verbose_name=["%d-%m-%Y"])),
            ],
            options={"db_table": "attendance",},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "rfid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("sid_id", models.IntegerField()),
                ("cid_id", models.IntegerField()),
                ("roll", models.CharField(max_length=11)),
            ],
            options={"db_table": "enrollment",},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["cid_id", "sid_id"], name="enrollment_cid_id_f67dd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["cid"], name="attendance_cid_59d6a3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance", unique_together={("rfid", "date")},
        ),
    ]
