# Generated by Django 3.0 on 2019-12-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rfid", models.IntegerField()),
                ("cid", models.IntegerField(db_index=True)),
                ("date", models.DateField(verbose_name=["%d-%m-%Y"])),
            ],
            options={"db_table": "attendance",},
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("section", models.CharField(max_length=20)),
            ],
            options={"db_table": "classroom",},
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={"db_table": "institution",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("contact_no", models.CharField(max_length=14)),
            ],
            options={"db_table": "student",},
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={"db_table": "teacher",},
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "rfid",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("roll", models.CharField(max_length=11)),
                (
                    "cid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.Classroom"
                    ),
                ),
                (
                    "sid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.Student"
                    ),
                ),
            ],
            options={"db_table": "enrollment",},
        ),
        migrations.AddField(
            model_name="classroom",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.Institution",
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data.Teacher"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["cid"], name="attendance_cid_59d6a3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="attendance", unique_together={("rfid", "date")},
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["cid", "sid"], name="enrollment_cid_id_f67dd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classroom",
            index=models.Index(fields=["teacher"], name="classroom_teacher_7f34cb_idx"),
        ),
    ]
